services:
  postgres:
    image: postgres:15-alpine
    container_name: ieee_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ieee
      POSTGRES_PASSWORD: ieee_password
      POSTGRES_DB: ieee_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: ieee_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - '9000:9000'   # API
      - '9001:9001'   # Console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  api:
    build: .
    container_name: ieee_api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://ieee:ieee_password@postgres:5432/ieee_db?schema=public
      JWT_REFRESH_SECRET: your-super-secret-refresh-key
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRATION: 7d
      PORT: 3000
      NODE_ENV: production

      # Vari√°veis do MinIO
      MINIO_ENDPOINT: ieee_minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123

    depends_on:
      - postgres
      - minio
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
  minio_data:

